[package]
name = "nft-io"
version = "0.2.10"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "testnet" }
gear-lib = { git = "https://github.com/gear-dapps/gear-lib.git", tag = "0.3.5" }
primitive-types = { version = "0.12.1", default-features = false }
gmeta = { git = "https://github.com/gear-tech/gear.git", features = ["codegen"], branch = "testnet" }
